repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
        -   id: end-of-file-fixer
        -   id: trailing-whitespace
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
        -   id: mypy
-   repo: https://github.com/pycqa/flake8
    rev: '3.8.4'
    hooks:
        -   id: flake8
            args: ['--max-line-length=120']
-   repo: local
    hooks:
        -   id: test
            name: Run tests
            always_run: true
            pass_filenames: false
            entry: 'python3 test.py'
            language: system
            verbose: true
